<?php
/**
 * @category    MT
 * @package     MT_Widget
 * @copyright   Copyright (C) 2008-2014 MagentoThemes.net. All Rights Reserved.
 * @license     GNU General Public License version 2 or later
 * @author      MagentoThemes.net
 * @email       support@magentothemes.net
 */
?>
<?php
/* @var $this MT_Widget_Block_Widget */
$_id                = $this->getConfig('id');
$_title             = $this->getConfig('widget_title');
$t                  = microtime();
?>
<div class="<?php echo $this->getConfig('classes') ?>" id="<?php echo $_id ?>">
    <?php if ($_title): ?>
        <h2><?php echo $_title ?></h2>
    <?php endif ?>
    <div class="row">
    <?php echo $this->renderCollection('collection', $this->getData('mode'), 'mt/widget/collection-position04.phtml') ?>
    </div>
</div>
<script type="text/javascript" src="<?php echo Mage::getBaseUrl('js') ?>mt/widget/frontend.js"></script>
<script type="text/javascript">
    new MT.Widget('<?php echo $_id ?>', {
        animation: <?php echo $this->getConfig('animation') ?>,
        parallax: <?php echo $this->getConfig('parallax') ?>,
        carousel: <?php echo $this->getConfig('carousel') ?>,
        carouselConfig:  {itemsCustom: [
            [0,1],
            [320,1],
            [360,1],
            [480,2],
            [640,2],
            [768,2],
            [800,2],
            [980,2],
            [1024,3],
            [1280,3]
        ]
        },
        countdown: <?php echo $this->getConfig('countdown') ?>,
        countdownConfig: null,
        countdownTemplate: '<div class="day"><span class="no">%d</span><span class="text">days</span></div><div class="hours"><span class="no">%h</span><span class="text">hours</span></div><div class="min"><span class="no">%i</span><span class="text">min</span></div><div class="second"><span class="no">%s</span><span class="text">secs</span></div>',
        kenburns: <?php echo $this->getConfig('kenburns') ?>
    });
</script>
<?php //Mage::log(microtime() - $t) ?>
